### ISSUE TITLE
Clarify exported API

### ISSUE THREAD

**Issue by calmh** [fgrid/itc#3]
Hi!

This looks like something I need and I wasn't aware if this type of clock before reading your announcement so thanks for that. I glanced through the paper and obviously need to study that a bit more. From a first impression, should the BitPacker etc (under whatever name) be exported? It seems like the public API really revolves around the Stamp type and the rest might be implementation details, or I might just not have grasped how to use it yet (still looking at the examples etc).

**Comment by stephanheinze** [comment]
You're right. BitPacker und BitUnPacker are implementation details and only here because it's declared in the paper's annex.
Conclusion: Encoding/Decoding a stamp should be declared as interface and BitPacker/BitUnPacker  should get a) a different name b) become default implementation for the interface c) get better documentation.
